const menuItemData = [
  {
    id: 1,
    title: "Raw Scallops from Erquy",
    description: "Candied Jerusalem artichokes, truffle",
    price: 40,
    category: "Starters",
    img: "https://i.ibb.co.com/jkSMzYh/Image-3.png",
  },
  {
    id: 2,
    title: "Spring Roll",
    description: "Candied Jerusalem artichokes, truffle",
    price: 20,
    category: "Starters",
    img: "https://i.ibb.co.com/NNhDF5s/Image-4.png",
  },
  {
    id: 3,
    title: "French Onion Soup",
    description: "Candied Jerusalem artichokes, truffle",
    price: 25,
    category: "Starters",
    img: "https://i.ibb.co.com/N1ZxZ7c/Image-5.png",
  },
  {
    id: 4,
    title: "Tomato Bruschetta",
    description: "Candied Jerusalem artichokes, truffle",
    price: 30,
    category: "Starters",
    img: "https://i.ibb.co.com/KrPMgYk/Image-6.png",
  },
  {
    id: 5,
    title: "Grilled Salmon with Dil Sauce",
    description: "GCandied Jerusalem artichokes, trufflee",
    price: 30,
    category: "Main Dish",
    img: "https://i.ibb.co.com/thCS1Cj/Image-7.png",
  },
  {
    id: 6,
    title: "RRoast Beef with Vegetable",
    description: "GCandied Jerusalem artichokes, trufflee",
    price: 40,
    category: "Main Dish",
    img: "https://i.ibb.co.com/MVTKvgf/Image-8.png",
  },
  {
    id: 7,
    title: "Marrkesh Vegetetarian Curruy",
    description: "GCandied Jerusalem artichokes, truffle",
    price: 40,
    category: "Main Dish",
    img: "https://i.ibb.co.com/vvFCj3N/Image-9.png",
  },
  {
    id: 8,
    title: "Spicy Vegan Potato Curry",
    description: "GCandied Jerusalem artichokes, truffle",
    price: 40,
    category: "Main Dish",
    img: "https://i.ibb.co.com/F7dsX1k/Image-10.png",
  },
  {
    id: 9,
    title: "Apple Pie with Cream",
    description: "GCandied Jerusalem artichokes, truffle",
    price: 40,
    category: "Dessert",
    img: "https://i.ibb.co.com/D1LTbSk/Image-11.png",
  },
  {
    id: 10,
    title: "Lemon Meringue Pie",
    description: "GCandied Jerusalem artichokes, truffle",
    price: 40,
    category: "Dessert",
    img: "https://i.ibb.co.com/Fbm7HFZ/Image-12.png",
  },
];

export { menuItemData };
